name: 'Deploy para aws CloudFormation'

on:
  push:
    branches: [main]
  # pull_request:
  #   branches: [main]

  workflow_dispatch:

jobs:
  readme_code:
    runs-on: ubuntu-latest
    steps:
      - name: Fazer checkout da branch
        uses: actions/checkout@v2

      - name: Configurar AWS
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: us-east-1

      - name: Deploy no CloudFormation
        uses: aws-actions/aws-cloudformation-github-deploy@v1
        with:
          name: dataops-lab3
          template: ec2-jenkins.yaml
          parameter-overrides: "key=vockey, iamprofile=LabInstanceProfile"
          # email: ${{ env.GIT_USER_EMAIL }}
          # user: ${{ env.GIT_USER_NAME }}
    